### ISSUE TITLE
"Replace all with code..." compile empty without errors

### ISSUE THREAD

**Issue by albe65** [sailro/Reflexil#107]
With this code using the "Replace all with code ..." compiling have no results without errors.
Without results obviously OK buttun is disabled
Can you help me?
[Here the full code](https://github.com/sailro/Reflexil/files/1199934/code.txt)

`static double smethod_28(double[] object_0, int int_0, int int_1)
	{

    int num4;
    double num = 0.0;
    double d = 0.0;
    int num3 = 0;
    int num5 = (int_0 >= object_0.Length) ? (object_0.Length - 1) : int_0;
    for (num4 = num5; num4 >= int_1; num4--)
    {
        num += object_0[num4];
        num3++;
    }
    num /= (double) num3;
    for (num4 = num5; num4 >= int_1; num4--)
    {
        d += Math.Pow(object_0[num4] - num, 2.0);
    }
    d /= (double) num3;
    d *= QuantTrader.Settings.TradingDaysPerYear;
    return Math.Sqrt(d);
	}`

**Comment by sailro** [comment]
Could you send me the original assembly? I need to repro this.

**Comment by sailro** [comment]
In my case the function does not have the same signature:
static double smethod_28(object object_0, int int_0, int int_1)

In your case
static double smethod_28(double[] object_0, int int_0, int int_1)

You CANNOT change the function signature in the "Replace All with Code" tool. That's why you have an empty Window, as Reflexil is unable to locate the proper prototype afterwards.

Perhaps this is due to the original obfuscation, but you have to stay with the original signature and adapt your code. Like this:

```c#
	// You can only reference methods or fields defined in the class (not in ancestors classes)
	// Fields and methods stubs are needed for compilation purposes only.
	// Reflexil will automaticaly map current type, fields or methods to original references.
	static double smethod_28(object object_0, int int_0, int int_1)
	{
		var dblarray = object_0 as double[];
		if (dblarray == null)
			return 0.0;
		
	    int num4;
	    double num = 0.0;
	    double d = 0.0;
	    int num3 = 0;
	    int num5 = (int_0 >= dblarray.Length) ? (dblarray.Length - 1) : int_0;
	    for (num4 = num5; num4 >= int_1; num4--)
	    {
	        num += dblarray[num4];
	        num3++;
	    }
	    num /= (double) num3;
	    for (num4 = num5; num4 >= int_1; num4--)
	    {
	        d += Math.Pow(dblarray[num4] - num, 2.0);
	    }
	    d /= (double) num3;
	    d *= QuantTrader.Settings.TradingDaysPerYear;
	    return Math.Sqrt(d);
	}
```
