### ISSUE TITLE
No match for type <PrivateImplementationDetails> {xxx}  in source assembly

### ISSUE THREAD

**Issue by zayyeh** [sailro/Reflexil#111]
Is there any way to overcome this? I've met this issue several times but could not quite understand when this message pops up: most of the times I replace all with code with no problem.

If you are curious, you can reproduce it with assembly I attached at #110. Just try to compile BuildingPanel_Classes > RefreshPanel() without any changes. Screenshot: http://prntscr.com/gfbxpw

EDIT: Same error in CodexClassPanel > PopulatePanel() - http://prntscr.com/gfsyt7

**Comment by sailro** [comment]
If you are using special switch constructs or array initializers, this can lead to generating this specific extra class (PrivateImplementation).

One example here:
http://bartdesmet.net/blogs/bart/archive/2008/08/21/how-c-array-initializers-work.aspx

This will not work with the injection code process, as we only inject the content of the targeted method, nothing more.

It is the exact same limitation with lambdas or IEnumerator constructs or async code, because the compiler will generate additional classes/methods for supporting those. 

This "replace all with code" is a nice feature, but comes with those limitations regarding compiler generated stuff.
