### ISSUE TITLE
About illegal operand

### ISSUE THREAD

**Issue by Neutron3529** [sailro/Reflexil#120]
I want to knoe if there're some method to avoid this alert?
![default](https://user-images.githubusercontent.com/26130174/35429869-d363c016-02b0-11e8-87a2-c3c3c46b4470.png)
i means, refiexil should have the ability to remove the illegal operand automatically to avoid this alert.

Anyway, thanks a lot for this great plugin

...firstly i wrote this issue for editing get method
i am a new MODer, so i don't know how to edit "get" method
when i saw a get method
![default](https://user-images.githubusercontent.com/26130174/35429632-dd757b22-02af-11e8-98b4-82e4793f78c3.png)
there seems no way to edit it.
![default](https://user-images.githubusercontent.com/26130174/35429780-78225cbc-02b0-11e8-8f88-992111648e4b.png)
but, it loos just like a normal method or function.

soon i realized how to do it
![default](https://user-images.githubusercontent.com/26130174/35430073-a5dd94c2-02b1-11e8-9093-aaeab63ac597.png)

**Comment by sailro** [comment]
Regarding editing properties, ILSpy will not show getter/setter if your current language is C#. Switch to IL/IL with C# to see associated getter/setter in ILSpy TreeView:

![image](https://user-images.githubusercontent.com/638167/35453262-612019aa-027e-11e8-8c56-ef2dd36c66b3.png)

Regarding "Reflexil should have the ability to remove the illegal operand automatically to avoid this alert.", I do not agree. Binary editing is an advanced usage, so the best thing is to master what you do instead of the tool magically removing stuff if you don't know what you are doing :)
