### ISSUE TITLE
Unable to save assembly

### ISSUE THREAD

**Issue by btlramesh** [sailro/Reflexil#13]
i can't save the file trowing the following error
"Reflexil is unable to save this assembly: Failed to resolve assembly: 'UnityEngine Version=0.0.0.0, Cutrue=neutral, PublicToken=null"

![reflexil-error](https://cloud.githubusercontent.com/assets/10597536/6430325/fb0a82a6-c02a-11e4-8bdc-f27400ba2850.jpg)

**Comment by sailro** [comment]
Hi. This should be solved with this preview release (with ILSpy in this case but the fix is also for Reflector):
https://www.dropbox.com/s/jdu8h32whqo6h30/reflexil.for.ILSpy.2.0-preview3.zip

If the problem persist, just add the Unity engine assembly to the assembly list of the host program (ILSpy or Reflector).
