### ISSUE TITLE
[Question] What does Optimize and Fix IL option do?

### ISSUE THREAD

**Issue by sunnygb** [sailro/Reflexil#131]
I am student, and pretty fond of reversing things. Recently option to optimize and fix IL got up my eyes and raised many questions
![image](https://user-images.githubusercontent.com/13783116/44847304-7c7fdd00-ac6c-11e8-8aa7-cac647ea6496.png)

1: What does this option does?
2: Does .dll assemblies already been optimized by the compiler before patching? why we need this then after patching?
3: Since its an option, and not a default option, could it has some kind of side effects?

**Comment by sailro** [comment]
With CIL, you have short forms instructions, like for branching, that are more compact because they use a byte instead of an int as operand.

Like:
br <int32 (target)>	Branch to target
br.s <int8 (target)>	Branch to target, short form.

When you add/edit instructions and the resulting binary code is increased in size, it may happen that one or more branching instructions in short form are overflowed.

When "Optimize and fix IL code" is enabled, Reflexil will check all short form instructions, replacing them with regular form if needed.

**Comment by sunnygb** [comment]
I heard that short forms of instructions are preferred where possible... so that assembler take up little space on hard and memory, 
Replacing short forms instructions with regular ones dosnt have side effects?
What u recommend if size of assembly becomes small or almost same?

**Comment by sailro** [comment]
No side effect except the size. In fact this option will work for both scenarios (increase or decrease in size). It will reevaluate all branching instructions and use either short or regular form depending on how far is the jump.

**Comment by sunnygb** [comment]
I missed the whole point up there...
Thanks for clarification..
