### ISSUE TITLE
Net Framework sign DLL

### ISSUE THREAD

**Issue by anilshivamber** [sailro/Reflexil#132]
hi when use refexil to edit it lose the signature how i can keep the signature or resign with the same signature

thank you

**Comment by UlyssesWu** [comment]
It's impossible to resign unless you have the private key (usually only kept by the developer).

**Comment by anilshivamber** [comment]
there have a guy editing a dll file and it stiff have the signature

**Comment by sailro** [comment]
When you edit/save an assembly with a strong name, you will have an assembly in a delay sign state.

As @UlyssesWu explained, you'll need the private key to resign (or add assembly verification exclusions to the registry).

**Comment by anilshivamber** [comment]
but then the dll would not be sign?

**Comment by sailro** [comment]
No.

We'll insert the **public key** into the assembly manifest and reserves space in the PE file for the full strong name signature. 

Because the assembly does not have anymore a valid strong name signature, the verification of that signature will fail if you try the .NET Strong Name tool.

Again, as @UlyssesWu explained, you'll need to resign with the proper **private key** if you have it.

Other options:
- disable assembly verification from the registry (only for the local computer so)
- resign with another key, but if this assembly is referenced by others, it will break.
