### ISSUE TITLE
CS0246 errors 

### ISSUE THREAD

**Issue by MoritzioM** [sailro/Reflexil#15]
First, thanks very much for Reflexil. I really like it but having some troubles using it for the first time.
(I posted this on CodeProject first, but this looks like the better place. Not sure how to flag it as a question.)
One:
See <a href="http://www.dropbox.com/s/b6zrwt9at6g3obx/Reflexil-CS0246.png?dl=0">this screenshot.</a>

I am using "Replace All With Code"  to recompile a method in a Unity game. I get a lot of these CS0246 errors ("The type or namespace "somenamehere" could not be found. (Are you using directive or an assembly reference?"

I am using the Unity/Silverlight compiler profile.

The types in error are all part of the parent DLL. I have tried to correct this by adding references to the types in the Import section but they all fail indicating a semicolon is missing but I can see it is there. I think I am doing that wrong.

I would really like to understand what to do to resolve these namespace errors.

Two: 
The second error is CS0436, indicating a CS file is in conflict in /user/username/appdata/local/temp. I do not see that file in that directory, nor do I know how it got there. See <a href="https://www.dropbox.com/s/ipc8yq8h8nkxex0/Reflexil-no-cs.png?dl=0">this screenshot.</a>

Three: 
Do I need to worry about all the files in the Reflexil.Persistence directory?
See <a href="http://www.dropbox.com/s/fm1vyax4wc9buf1/Reflexil-Persistance.png?dl=0">this screenshot</a>

-Mo

**Comment by sailro** [comment]
One:
Those errors are often related to:
- missing references, you can add them using Reflexil in the host applicaion
- missing imports, be careful when using Types
- when using Replace All with code, we cannot access non public members (because we are in the context of another assembly), so change scopes first.

Two:
No idea on this one and the screenshot is no more available.

Three:
No, the purpose of this is to cache intellisense data.
