### ISSUE TITLE
Bug CS0656

### ISSUE THREAD

**Issue by doxuto** [sailro/Reflexil#36]
I am using "Replace All With Code" to recompile a method in a Unity game.I use compile the unity/sliverLight  error Missing compiler required member System.Runtime.CompilerServices.ExtensionAttribute..ctor
How to fix it

**Comment by sailro** [comment]
Hello,

Can you give me your assembly and repro steps please.

Seems related to extension methods.

Thanks

**Comment by justinpierson** [comment]
I have found a workaround to this issue... it is due to the mscorlib.dll. What I found was when you select a unity profile it appends the /nostdlib to the csc and the mscorlib.dll that is used in unity does not work with 4.0 csc.exe (gives that odd emit error)
What I did was create a new compiler profile, with 4.0 as the compiler and in the GetReferences method I filter out the system/mscorlib and not not add them to the references, this allows the compiler to auto use the correct versions and it then can compile.

**Comment by Quillbert** [comment]
How would I go about doing that?
