### ISSUE TITLE
Properties not supported in 'Replace all with code'

### ISSUE THREAD

**Issue by BlueRaja** [sailro/Reflexil#45]
When compiling using 'Replace all with code', properties are not supported.  For every instance of `MyProp`, I need to replace it with `set_MyProp()` or `get_MyProp()`.

This can be very time-consuming when I am copying+pasting the original method code, as a large method could use dozens of properties.

**Comment by sailro** [comment]
Agree. I think I've just to generate the property stub and it should work, as the compiler will translate this to calls to getter/setter. Did you ever try to do that to see ?

**Comment by BlueRaja** [comment]
No, I haven't tried that.  I'll try it next time I'm playing around with Unity decompilation.

**Comment by BlueRaja** [comment]
Yes, this worked (though I had to manually find/delete the `get_*` and `set_*` methods).

**Comment by BlueRaja** [comment]
It's unfortunate that this and similar requests (like #31) are marked as `wontfix` - it severely limits the usability/usefulness of Reflexil if editing one line of code, which should take two clicks, takes 10-15 minutes.  Is it a matter of the API not allowing this for some reason, or do you just not have the time?

If it's the latter, maybe I can look into adding these features.  What would need to be done?  Where in the code would I do it?

**Comment by sailro** [comment]
Yep sorry for not giving you enough details. In fact this is not as simple as editing your code in Visual Studio. We are in very very different context and we have to integrate a small portion of compiled code in a whole assembly. 

For that we have to patch all references to existing fields/methods/types. This is often complex and due to limitations (we have to compile a new assembly and extract what we need, then replace parts in an existing one) we are often unable to compile "decompiled code provided by the host (ILSpy/Reflector/JustDecompile)".

Same thing for properties, which can lead to very advanced edge cases, especially if end users start to alter setter/getter...

Thanks!

**Comment by BlueRaja** [comment]
I am still of the mind of "always make the common case the default", which in this case would be definitely be defaulting the method to the existing code.  Edge cases do not change that.
