### ISSUE TITLE
Install on ILSpy?

### ISSUE THREAD

**Issue by alexreg** [sailro/Reflexil#47]
Instructions on how to install Reflexil would be much appreciated, since there is no README, and this information is not readily available.

**Comment by UlyssesWu** [comment]
It's really easy.
Put the `Reflexil.ILSpy.Plugin.dll`(AIO) file into the ILSpy directory.
Open ILSpy(2.0+), select "View" menu and you will see "Reflexil 2.0".

**Comment by alexreg** [comment]
Yeah, I realised this eventually, but it’s kind of ugly to have to dump all the DLLs in there. I suppose that’s what the “AIO” (all-in-one) version is for, now that I know what it is!

**Comment by webmasterMeyers** [comment]
+1 on docs

**Comment by SamB** [comment]
Yeah, if you were to add a note that AIO means "all in one dll"/merged assembly at the bottom of the release notes, that would make it a *lot* easier to figure out what to do next. Because what happens now is the typical user is like "what is AIO? is that a dependency, or a type of build?".  (I mean, assuming I'm a typical user. That isn't usually a safe assumption, but given that we're talking about a plugin for decompilers, I think it's a bit safer than usual.)

**Comment by NaNraptor** [comment]
Bump for this, AIO meant nothing to me in this context, or lack thereof (I first tought of water coolers lol). Only figured out what I need to do thanks to this issue
