### ISSUE TITLE
Can I use this to view a entire form that does not display at all in ILSpy

### ISSUE THREAD

**Issue by AraHaan** [sailro/Reflexil#69]
ILSpy has this Error with the particular assembly here that not only the form cs file can be saved but the generated project file would be 0 kb when it should be at least there.

https://github.com/icsharpcode/ILSpy/issues/713

Sorry about this issue but I need to know for sure as it is needed to build a working Translation of the Japanese Assemblies here. And hopefully save their code on a github repo for anyone to access.

**Comment by UlyssesWu** [comment]
I tested PMDEditor 0139 with ILSpy and yes, it has the same error. It can be avoided by turn off "Decompile anonymous methods/lambda" in Options. But the code saved will still be hard to use (I mean, recompile).

You can try other decompilers like JustDecompile or DnSpy (forked and enhanced from ILSpy), both of them is free. 

In fact, I don't think you need to decompile an assembly, modify and recompile it to translate it. Usually we just extract the texts, make translations and then replace the texts. Of course Reflexil is able to replace texts (manually), but you may need tools which are more _automatic_.

**Comment by AraHaan** [comment]
they found where it is at with that enabled and will pull the fix for the next version of ILSpy thanks to the assembly I sent them.

**Comment by UlyssesWu** [comment]
OK, you just need to know you should not release the code from PMDEditor. And still, you may find it tedious to recompile, while replacing texts might be a better solution for localization.

Turn back to your issue:

Reflexil is a tool to modify assemblies, it's not a decompiler, but a plugin for ILSpy, Reflector and JD, and it won't change the host's decompilation engine. That means the answer to "Can I use this to view a entire form that does not display at all in ILSpy" is **NO**. (But if you want to see IL rather than C#, yes)

If you now have no question anymore, please close this issue.
