### ISSUE TITLE
Add "Edit Code" option

### ISSUE THREAD

**Issue by LennyPenny** [sailro/Reflexil#85]
Would be awesome if there was a way to insert the decompiled C# code (including all imports of the class) of the current method into the window that pops up when selecting "Replace all with code" in the context menu. 
That would decrease the copy and pasting needed when trying to edit a method by a lot. (I tried to find the code that creates the window myself but I couldn't find it)

**Comment by Splamy** [comment]
Btw this issue already was here in #31 and was closed with 'wont fix'

**Comment by LennyPenny** [comment]
That's a shame then, maybe I can find a way to hack it in myself

**Comment by MulleDK19** [comment]
I vote that this be re-opened. Issue #31 is NOT the same as this issue. #31 seems to suggest allowing editing multiple methods at the same time, by filling all the stubs with actual code and allow them all to be changed at once.

#85 however, suggests an option like "Replace All With Code", where the decompiled code is pasted into the body of the edited function, so you can edit, instead of replacing.

Eg. you edit "HelloWorld()" and it'll pop up the same way as "Replace All With Code", but the HelloWorld() body will contain the decompiled code, and the usings for it will be included, so that you can edit the code.

Right now, you can copy/paste the decompiled code manually into the "Replace All With Code" window, but you then have to either add usings manually, or change the code to use fully qualified identifiers, which is a hassle.

This shouldn't be too difficult to implement.
