### ISSUE TITLE
version 2.1 still complains CS1703 when modify mono assembly

### ISSUE THREAD

**Issue by beyonddoor** [sailro/Reflexil#86]
I use reflexil in unity assembly, click menu **"replace all with code..."**, and it complains CS1703 issue, my assembly references `mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e`, but `C:\Windows\assembly\GAC_32\mscorlib\2.0.0.0__b77a5c561934e089\mscorlib.dll, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` is wrongly imported, I even cannot remove it from GAC using `gacutil /u`. any helps?

**Comment by sailro** [comment]
Hi. When replacing code, it's possible to specify a profile. When using the SilverLight/Unity profile, it should compiles as expected.

Reflexil should enable this profile by default, but as described in #79, it seems that sometimes this is not the case. So could you share your assemby so that I could have a look ?

Thanks

**Comment by beyonddoor** [comment]
Hi Sailro, sorry to reply you so late, I have forgot the assembly troubled me, I test a simple one and it works as expected. I will share the assembly when the same issue happens again.

**Comment by sailro** [comment]
Okay, I will close the issue. Let's reopen if you find something
